import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar/navbar";
import Footer from "@/components/Footer/footer";
import SpeedDial from "@/components/SpeedDial/speed-dial";

const openSans = Open_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-open-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${openSans.variable} font-sans`}>
        <NavBar />
        <main className="min-h-screen">{children}</main>
        <SpeedDial />
        <Footer />
      </body>
    </html>
  );
}
